global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Multi-Agent API
  - job_name: 'multi-agent-api'
    static_configs:
      - targets: ['multi-agent-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  # Node exporter (if added)
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
